name: New Episode Issue generate
on:
  schedule:
  - cron: '0 0 * * 1'  # At 09:00 on Monday(JST), https://crontab.guru/
  workflow_dispatch:

jobs:
  issue_generate:
    name: Create Episode Standup
    runs-on: ubuntu-latest
    steps:

    # Repo code checkout required if `template` is used
    - name: Checkout
      uses: actions/checkout@v2

    # https://stackoverflow.com/a/60942437
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(TZ=Asia/Tokyo date +'%Y/%m/%d')"

    - name: Scheduled New Issue with Github Actions
      uses: imjohnbo/issue-bot@v2.3
      with:
        title: ${{ steps.date.outputs.date }} - エピソードxxx
        assignees: "" # Github Account name without @.
        labels: "episode"
        pinned: false
        close-previous: false
        template: ".github/ISSUE_TEMPLATE/episode-template.md"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
